version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: highclass-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: highclassdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata_highclass:/var/lib/postgresql/data

volumes:
  pgdata_highclass:
