-- AlterTable
ALTER TABLE "Contract" ADD COLUMN     "buyer_address" TEXT,
ADD COLUMN     "buyer_cep" VARCHAR(9),
ADD COLUMN     "buyer_cpf" VARCHAR(14),
ADD COLUMN     "buyer_name" TEXT,
ADD COLUMN     "buyer_rg" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "commission_agency" TEXT,
ADD COLUMN     "commission_bank" TEXT,
ADD COLUMN     "commission_checking_account" TEXT,
ADD COLUMN     "commission_cpf" VARCHAR(18),
ADD COLUMN     "commission_name" TEXT,
ADD COLUMN     "commission_value" DECIMAL(15,2),
ADD COLUMN     "commission_value_written" VARCHAR(500),
ADD COLUMN     "payment_seller_value" DECIMAL(15,2),
ADD COLUMN     "payment_seller_value_written" VARCHAR(500),
ADD COLUMN     "seller_address" TEXT,
ADD COLUMN     "seller_agency" TEXT,
ADD COLUMN     "seller_bank" TEXT,
ADD COLUMN     "seller_cep" VARCHAR(9),
ADD COLUMN     "seller_checking_account" TEXT,
ADD COLUMN     "seller_cpf" VARCHAR(14),
ADD COLUMN     "seller_name" TEXT,
ADD COLUMN     "seller_rg" TEXT,
ADD COLUMN     "signed_pdf_url" TEXT,
ADD COLUMN     "template_id" TEXT,
ADD COLUMN     "vehicle_model" TEXT,
ADD COLUMN     "vehicle_price" DECIMAL(15,2),
ADD COLUMN     "vehicle_price_written" VARCHAR(500),
ADD COLUMN     "vehicle_registration_id" TEXT,
ADD COLUMN     "vehicle_serial_number" TEXT,
ADD COLUMN     "vehicle_technical_information" TEXT,
ADD COLUMN     "vehicle_year" TEXT,
ALTER COLUMN "file_name" DROP NOT NULL,
ALTER COLUMN "file_path" DROP NOT NULL,
ALTER COLUMN "file_type" DROP NOT NULL,
ALTER COLUMN "file_size" DROP NOT NULL,
ALTER COLUMN "original_pdf_url" DROP NOT NULL;
